"""Add profile image

Revision ID: 90701686a766
Revises: 0675d078256b
Create Date: 2025-04-30 23:04:22.989006

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90701686a766'
down_revision = '0675d078256b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_image', sa.String(length=250), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('profile_image')

    # ### end Alembic commands ###
